### PR TITLE
(#8) Insert body contents, not body tag

### LINKED ISSUE #8: CIS slider inserts second body tag
### Issue description
When the CIS slider JavaScript executes on a window, it is inserting a second `<body>` tag inside of the main `<body>` tag. This breaks the Drupal moderation sidebar module, which is looking for the `<body>` tag to update and accidentally updates the second tag instead of the first. (It would likely break other Drupal-based modals too.)

Problem is here:

https://github.com/NCIOCPL/cis-slider/blob/f4533dddf8be661535e44386d5cb2ca0a5e568d3/src/main.ts#L113

We are inserting the `<body>` tag parsed out of the HTML, not the contents of it.

In the short-run, we have disabled the CIS Slider on `www-cms` to make sure nothing breaks. We should undo that when this is fixed.

### Steps to reproduce the issue

1.  Load the test page in the repo
2. View the DOM and see the double'd `<body>` tag

### What's the expected result?
- No second body tag

### What's the actual result?
- A doubled body tag

### Additional details / screenshot

body-tag

### PR DESCRIPTION
**Pull request by jfrank-nih**
Closes #8

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -110,7 +110,8 @@ const initComponents = () => {
 	// Inject modal dialog.
 	const parser = new DOMParser();
 	const dialog = parser.parseFromString(content, 'text/html');
-	const modalContents = document.body.appendChild(dialog.body);
+	const firstDiv = dialog.body.querySelector('div') || document.createElement('div');
```
Comment (bryanpizzillo) [inline src/main.ts:113]: I see what you are doing here, but this would not account for either multiple elements in the HTML, or a change to the elements types themselves. (.e.g, a change from a `<div>` to a `<dialog>`). 

I think the best course of action is to insert a dummy div and then append the children of body to that. I can take a stab at it later today.

**Comment by welshja** [comment]
Testing steps:
1. Updated launch rule to point to dev js file with this change: https://static-dev.cancer.gov/launchables/cis-slider/pr-9/assets/cis-slider-QZO59nQz.js
2. Removed launch conditions that blocked this from appearing on pages while users are editing in the CMS
3. Built these changes in a library to Development environment
4. Went into [www-cms-dev](https://www-cms-dev.cancer.gov/about-cancer/diagnosis-staging/symptoms)
5. Updated Adobe Analytics debugger to point to development library with rule change
6. Confirmed I was now seeing the questions button within the editing interface
7. Clicked on Tasks in the CMS page, and I can see content

image

**Review by jfrank-nih — COMMENTED** [review]
Looks good
